package me.itangqi.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CACHE.
 */
public class Cache {

    private Long id;
    /** Not-null value. */
    private String imgPath;
    private int pxScreenHeight;

    public Cache() {
    }

    public Cache(Long id) {
        this.id = id;
    }
    public Cache(String imgPath, int pxScreenHeight) {
        this.imgPath = imgPath;
        this.pxScreenHeight = pxScreenHeight;
    }
    public Cache(Long id, String imgPath, int pxScreenHeight) {
        this.id = id;
        this.imgPath = imgPath;
        this.pxScreenHeight = pxScreenHeight;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getImgPath() {
        return imgPath;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }

    public int getPxScreenHeight() {
        return pxScreenHeight;
    }

    public void setPxScreenHeight(int pxScreenHeight) {
        this.pxScreenHeight = pxScreenHeight;
    }

}
